service: blog

image: ignatiuswisesa/blog

servers:
  - 3.106.145.17

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/KeyPair.pem

registry:
  username: ignatiuswisesa
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "blog_storage:/rails/storage"
  - "blog_db:/rails/db"

builder:
  arch: amd64

proxy:
  ssl: false
  host: 3.106.145.17

healthcheck:
  path: /up
  interval: 10s
  timeout: 5s
  retries: 6
  start_period: 40s
